# Generated by Django 5.1.1 on 2024-09-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('instruções', models.TextField()),
                ('postado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
